amc: Fix build failure with gcc 16 due to used variable
hal/amc/redfish.cpp: In member function ‘int redfish::discoverIntelGpusHttpScan(const std::string&, RedfishGPUDevice*, int, int*) const’:
hal/amc/redfish.cpp:537:13: error: variable ‘parseIndex’ set but not used [-Werror=unused-but-set-variable=]

Signed-off-by: Alexander Kanevskiy <alexander.kanevskiy@intel.com>