oal: Fix build failure with gcc 16 due to used variable
oal/lin/lin.cpp: In function ‘void getSwitchDevicePath(hwloc_obj_t, std::string*)’:
oal/lin/lin.cpp:474:13: error: variable ‘count’ set but not used [-Werror=unused-but-set-variable=]

Signed-off-by: Alexander Kanevskiy <alexander.kanevskiy@intel.com>